"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Professional = { id: string; name: string; specialty: string; active: boolean };
type Appointment = { id: string; professional_id: string; customer_name: string; customer_phone: string; service_name: string; appointment_date: string; start_time: string; end_time: string; status: "confirmed" | "completed" | "cancelled" | "no_show"; confirmation_state: "pending" | "confirmed"; confirmation_sent_at: string | null; confirmed_at: string | null };
type Business = { name: string; whatsapp_confirmation_template: string };

function localToday() { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function baseHours() { return Array.from({ length: 21 }, (_, i) => { const total=8*60+i*30; return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`; }); }
function formatDate(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"});}
function formatDateTime(value:string){return new Date(value).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}
function digits(value:string){return value.replace(/\D/g,"");}

export function AgendaBoard({ businessId }: { businessId: string }) {
  const supabase=useMemo(()=>createClient(),[]);
  const [date,setDate]=useState(localToday());
  const [professionals,setProfessionals]=useState<Professional[]>([]);
  const [appointments,setAppointments]=useState<Appointment[]>([]);
  const [business,setBusiness]=useState<Business|null>(null);
  const [selected,setSelected]=useState<Appointment|null>(null);
  const [loading,setLoading]=useState(true);
  const [updating,setUpdating]=useState(false);
  const [error,setError]=useState("");

  useEffect(()=>{let active=true;async function load(){setLoading(true);setError("");const[p,a,b]=await Promise.all([
    supabase.from("professionals").select("id,name,specialty,active").eq("business_id",businessId).eq("active",true).order("name"),
    supabase.from("appointments").select("id,professional_id,customer_name,customer_phone,service_name,appointment_date,start_time,end_time,status,confirmation_state,confirmation_sent_at,confirmed_at").eq("business_id",businessId).eq("appointment_date",date).neq("status","cancelled").order("start_time"),
    supabase.from("businesses").select("name,whatsapp_confirmation_template").eq("id",businessId).single(),
  ]);if(!active)return;if(p.error||a.error||b.error)setError((p.error||a.error||b.error)?.message??"Não foi possível carregar a agenda.");else{setProfessionals((p.data??[])as Professional[]);setAppointments((a.data??[])as Appointment[]);setBusiness(b.data as Business);}setLoading(false);}void load();return()=>{active=false};},[businessId,date,supabase]);

  const hours=useMemo(()=>[...new Set([...baseHours(),...appointments.map(i=>i.start_time.slice(0,5))])].sort(),[appointments]);
  function moveDay(amount:number){const next=new Date(`${date}T12:00:00`);next.setDate(next.getDate()+amount);setDate(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,"0")}-${String(next.getDate()).padStart(2,"0")}`);}
  function professionalName(a:Appointment){return professionals.find(p=>p.id===a.professional_id)?.name??"Profissional";}
  function whatsappUrl(a:Appointment){const template=business?.whatsapp_confirmation_template||"Olá, {cliente}! Seu horário para {servico} foi confirmado para o dia {data}, às {horario}, com {profissional}. Nós da {estabelecimento} aguardamos você ansiosamente!";const message=template.replaceAll("{cliente}",a.customer_name).replaceAll("{servico}",a.service_name).replaceAll("{data}",formatDate(a.appointment_date)).replaceAll("{horario}",a.start_time.slice(0,5)).replaceAll("{profissional}",professionalName(a)).replaceAll("{estabelecimento}",business?.name??"nosso estabelecimento");let phone=digits(a.customer_phone||"");if(phone&&phone.length<=11)phone=`55${phone}`;return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;}

  async function updateConfirmation(a:Appointment, sent=false){setUpdating(true);setError("");const now=new Date().toISOString();const patch={confirmation_state:"confirmed",confirmed_at:a.confirmed_at??now,...(sent?{confirmation_sent_at:now}:{})};const{error:updateError}=await supabase.from("appointments").update(patch).eq("id",a.id).eq("business_id",businessId);if(updateError)setError(updateError.message);else{const updated={...a,...patch} as Appointment;setAppointments(list=>list.map(item=>item.id===a.id?updated:item));setSelected(updated);}setUpdating(false);}
  async function sendWhatsapp(a:Appointment){window.open(whatsappUrl(a),"_blank","noopener,noreferrer");await updateConfirmation(a,true);}

  return <div className="content">
    <div className="page-heading"><div><h1>Agenda</h1><p>Clique em um atendimento para ver os dados e confirmar com o cliente.</p></div><a className="button button-primary" href="/painel/agendamentos">+ Novo agendamento</a></div>
    {error&&<div className="notice-box" style={{marginBottom:16}}>{error}</div>}
    <div className="agenda-toolbar card"><div className="agenda-date-controls"><button className="icon-button" onClick={()=>moveDay(-1)}>‹</button><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="icon-button" onClick={()=>moveDay(1)}>›</button></div><strong>{new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}</strong><span className="table-muted">{appointments.length} atendimento(s)</span></div>
    {loading?<div className="card empty-state"><h3>Carregando agenda...</h3></div>:professionals.length?<div className="card agenda-grid-wrap"><div className="agenda-grid" style={{gridTemplateColumns:`82px repeat(${professionals.length}, minmax(180px, 1fr))`}}><div className="agenda-corner">Horário</div>{professionals.map(p=><div className="agenda-professional" key={p.id}><div className="profile-avatar small-avatar">{p.name.slice(0,1).toUpperCase()}</div><div><strong>{p.name}</strong><span>{p.specialty}</span></div></div>)}{hours.flatMap(hour=>[<div className="agenda-time" key={`time-${hour}`}>{hour}</div>,...professionals.map(p=>{const matches=appointments.filter(a=>a.professional_id===p.id&&a.start_time.slice(0,5)===hour);return <div className="agenda-cell" key={`${p.id}-${hour}`}>{matches.map(a=><button type="button" className={`agenda-appointment status-${a.status}`} style={{width:"100%",textAlign:"left",cursor:"pointer",border:a.confirmation_state==="confirmed"?"2px solid rgba(34,197,94,.75)":"2px solid rgba(245,158,11,.65)",boxShadow:a.confirmation_state==="confirmed"?"0 0 0 3px rgba(34,197,94,.12)":"none",borderRadius:12}} key={a.id} onClick={()=>setSelected(a)}><strong>{a.customer_name} {a.confirmation_state==="confirmed"?"✓":""}</strong><span>{a.service_name}</span><small>{a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</small><small style={{display:"block",marginTop:4,fontWeight:700}}>{a.confirmation_state==="confirmed"?"Confirmado":"Aguardando confirmação"}</small></button>)}</div>})])}</div></div>:<div className="card empty-state"><h3>Nenhum profissional ativo</h3></div>}
    {selected&&<div role="presentation" onClick={()=>setSelected(null)} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.55)",display:"grid",placeItems:"center",padding:20}}><section role="dialog" aria-modal="true" className="card" onClick={e=>e.stopPropagation()} style={{width:"min(100%,540px)",padding:24}}><div style={{display:"flex",justifyContent:"space-between",gap:16}}><div><span className="eyebrow">Detalhes do agendamento</span><h2 style={{margin:"8px 0"}}>{selected.customer_name}</h2><span style={{fontWeight:800,color:selected.confirmation_state==="confirmed"?"rgb(22,163,74)":"rgb(217,119,6)"}}>{selected.confirmation_state==="confirmed"?"✓ Confirmado":"● Aguardando confirmação"}</span></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,margin:"20px 0"}}><div className="notice-box"><small>Serviço</small><strong style={{display:"block"}}>{selected.service_name}</strong></div><div className="notice-box"><small>Profissional</small><strong style={{display:"block"}}>{professionalName(selected)}</strong></div><div className="notice-box"><small>Data</small><strong style={{display:"block"}}>{formatDate(selected.appointment_date)}</strong></div><div className="notice-box"><small>Horário</small><strong style={{display:"block"}}>{selected.start_time.slice(0,5)}–{selected.end_time.slice(0,5)}</strong></div><div className="notice-box" style={{gridColumn:"1/-1"}}><small>WhatsApp</small><strong style={{display:"block"}}>{selected.customer_phone||"Não informado"}</strong></div></div>{selected.confirmation_sent_at&&<div className="notice-box" style={{marginBottom:16,border:"1px solid rgba(34,197,94,.45)"}}><strong>✓ Confirmação enviada pelo WhatsApp</strong><p style={{margin:"6px 0 0"}}>{formatDateTime(selected.confirmation_sent_at)}</p></div>}<div style={{display:"flex",gap:10,justifyContent:"flex-end",flexWrap:"wrap"}}>{selected.confirmation_state!=="confirmed"&&<button className="button button-secondary" disabled={updating} onClick={()=>void updateConfirmation(selected,false)}>{updating?"Salvando...":"Marcar como confirmado"}</button>}<button className="button button-primary" disabled={updating||!selected.customer_phone} onClick={()=>void sendWhatsapp(selected)}>{selected.confirmation_sent_at?"Reenviar no WhatsApp":"Enviar confirmação no WhatsApp"}</button></div></section></div>}
  </div>;
}
