"use client";

import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Step="service"|"professional"|"date"|"time"|"customer"|"review"|"success";
type Business={id:string;name:string;slug:string;segment:string;phone:string;city:string;address:string;public_description:string;minimum_notice_hours:number;booking_window_days:number;slot_step_minutes:number;theme:string;show_prices_publicly:boolean;show_professional_specialty:boolean;require_professional_confirmation:boolean;logo_url:string;cover_url:string;instagram_url:string;primary_color:string;opening_hours_text:string};
type Service={id:string;name:string;price:number;duration_minutes:number;professional_ids:string[]};
type Professional={id:string;name:string;specialty:string;photo_url:string};
type BookingData={business:Business;services:Service[];professionals:Professional[]};
const stepOrder:Step[]=["service","professional","date","time","customer","review","success"];
const labels:Record<Step,string>={service:"Serviço",professional:"Profissional",date:"Data",time:"Horário",customer:"Seus dados",review:"Revisar",success:"Concluído"};
function localDate(offset=0){const v=new Date();v.setDate(v.getDate()+offset);return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,"0")}-${String(v.getDate()).padStart(2,"0")}`;}
function formatDate(value:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(new Date(`${value}T12:00:00`));}
function endTime(start:string,duration:number){const[h,m]=start.split(":").map(Number);const t=h*60+m+duration;return `${String(Math.floor(t/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`;}
function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);}
function whatsapp(value:string){let p=value.replace(/\D/g,"");if(p&&p.length<=11)p=`55${p}`;return `https://wa.me/${p}`;}

export function PublicBooking({slug}:{slug:string}){
 const supabase=useMemo(()=>createClient(),[]);const[step,setStep]=useState<Step>("service");const[data,setData]=useState<BookingData|null>(null);const[loaded,setLoaded]=useState(false);const[serviceId,setServiceId]=useState("");const[professionalId,setProfessionalId]=useState("");const[date,setDate]=useState("");const[time,setTime]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[slots,setSlots]=useState<string[]>([]);const[loadingSlots,setLoadingSlots]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{async function load(){setLoaded(false);const{data:result,error:rpcError}=await(supabase as any).rpc("get_public_booking_data",{p_slug:slug});if(rpcError)setError("Não foi possível carregar esta agenda.");else if(result){setData(result as BookingData);document.documentElement.dataset.theme=result.business.theme||"system";}setLoaded(true);}void load();},[slug,supabase]);
 const selectedService=data?.services.find(i=>i.id===serviceId);const eligibleProfessionals=data?.professionals.filter(i=>selectedService?.professional_ids.includes(i.id))??[];const selectedProfessional=data?.professionals.find(i=>i.id===professionalId);const progress=Math.min(100,((stepOrder.indexOf(step)+1)/6)*100);const business=data?.business;const manual=Boolean(business?.require_professional_confirmation);const accent=business?.primary_color||"#7c3aed";
 async function loadSlots(nextDate=date){if(!selectedService||!selectedProfessional||!nextDate)return;setLoadingSlots(true);setError("");setTime("");const{data:result,error:rpcError}=await(supabase as any).rpc("get_public_available_slots",{p_slug:slug,p_service_id:selectedService.id,p_professional_id:selectedProfessional.id,p_date:nextDate});if(rpcError){setSlots([]);setError("Não foi possível consultar os horários. Tente novamente.");}else setSlots((result??[]).map((i:{slot:string}|string)=>typeof i==="string"?i:i.slot));setLoadingSlots(false);}
 function go(next:Step){setError("");setStep(next);window.scrollTo({top:0,behavior:"smooth"});}
 function chooseService(id:string){setServiceId(id);setProfessionalId("");setDate("");setTime("");setSlots([]);}function chooseProfessional(id:string){setProfessionalId(id);setDate("");setTime("");setSlots([]);}
 async function confirm(){if(!selectedService||!selectedProfessional||!date||!time||!name.trim()||!phone.trim())return;setSaving(true);setError("");const{error:rpcError}=await(supabase as any).rpc("create_public_appointment",{p_slug:slug,p_service_id:selectedService.id,p_professional_id:selectedProfessional.id,p_date:date,p_start:time,p_customer_name:name.trim(),p_customer_phone:phone.trim()});if(rpcError){setError(rpcError.message.includes("não está mais disponível")?"Esse horário acabou de ficar indisponível. Escolha outro horário.":rpcError.message);await loadSlots(date);setStep("time");}else go("success");setSaving(false);}
 if(loaded&&!data)return <main className="public-booking-shell"><section className="public-unavailable card"><h1>Agenda não encontrada</h1><p>Confira o endereço enviado pelo estabelecimento.</p></section></main>;
 return <main className="public-booking-shell" style={{["--public-accent" as string]:accent}}>
  <style>{`.public-booking-shell .button-primary,.public-booking-shell .booking-success-icon{background:var(--public-accent)!important}.public-booking-shell .public-progress>div{background:var(--public-accent)!important}.public-booking-shell .choice-card.selected,.public-booking-shell .professional-choice.selected,.public-booking-shell .slot-grid button.selected{border-color:var(--public-accent)!important;box-shadow:0 0 0 2px color-mix(in srgb,var(--public-accent) 22%,transparent)!important}.salon-cover{height:190px;border-radius:0 0 28px 28px;background:linear-gradient(135deg,color-mix(in srgb,var(--public-accent) 75%,#111),var(--public-accent));background-size:cover;background-position:center}.salon-identity{margin:-58px auto 20px;position:relative;display:flex;gap:18px;align-items:flex-end;padding:0 18px;max-width:760px}.salon-logo{width:116px;height:116px;border-radius:30px;object-fit:cover;border:5px solid var(--background,#fff);background:var(--public-accent);display:grid;place-items:center;color:white;font-size:42px;font-weight:800}.salon-title{padding-bottom:8px}.salon-title h1{margin:0 0 5px;font-size:clamp(1.55rem,5vw,2.2rem)}.salon-title p{margin:0}.salon-links{display:flex;flex-wrap:wrap;gap:8px;max-width:760px;margin:0 auto 18px;padding:0 18px}.salon-links a,.salon-links span{padding:9px 12px;border:1px solid var(--border);border-radius:999px;text-decoration:none;color:inherit;font-size:.9rem}.salon-about{max-width:760px;margin:0 auto 20px;padding:0 18px}.salon-about p{margin:0 0 8px}.professional-photo{width:72px!important;height:72px!important;border-radius:50%!important;object-fit:cover!important;font-size:0!important}.public-powered{opacity:.65;font-size:.78rem}@media(max-width:520px){.salon-cover{height:150px}.salon-identity{align-items:center;margin-top:-46px}.salon-logo{width:92px;height:92px;border-radius:24px}.salon-title{padding-top:44px}}`}</style>
  <div className="salon-cover" style={business?.cover_url?{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.25)),url(${business.cover_url})`}:undefined}/>
  <section className="salon-identity">{business?.logo_url?<img className="salon-logo" src={business.logo_url} alt={`Logo de ${business.name}`}/>:<div className="salon-logo">{business?.name.slice(0,1)||"S"}</div>}<div className="salon-title"><h1>{business?.name||"Carregando..."}</h1><p>{[business?.segment,business?.city].filter(Boolean).join(" · ")}</p></div></section>
  <div className="salon-links">{business?.phone&&<a href={whatsapp(business.phone)} target="_blank" rel="noreferrer">WhatsApp</a>}{business?.instagram_url&&<a href={business.instagram_url.startsWith("http")?business.instagram_url:`https://instagram.com/${business.instagram_url.replace("@","")}`} target="_blank" rel="noreferrer">Instagram</a>}{business?.address&&<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(business.address)}`} target="_blank" rel="noreferrer">Como chegar</a>}{business?.opening_hours_text&&<span>Horários disponíveis abaixo</span>}</div>
  {(business?.public_description||business?.opening_hours_text)&&<section className="salon-about">{business.public_description&&<p>{business.public_description}</p>}{business.opening_hours_text&&<small style={{whiteSpace:"pre-line"}}><strong>Funcionamento:</strong><br/>{business.opening_hours_text}</small>}</section>}
  {step!=="success"&&<><div className="public-progress"><div style={{width:`${progress}%`}}/></div><div className="public-step-title"><small>Etapa {stepOrder.indexOf(step)+1} de 6</small><strong>{labels[step]}</strong></div></>}
  <section className="public-booking-card card">{error&&<div className="public-error">{error}</div>}
  {step==="service"&&<><div className="public-heading"><h2>Escolha seu serviço</h2><p>Você está agendando diretamente com {business?.name}.</p></div><div className="choice-list">{data?.services.map(s=><button className={`choice-card ${serviceId===s.id?"selected":""}`} key={s.id} onClick={()=>chooseService(s.id)}><div><strong>{s.name}</strong><span>{s.duration_minutes} min</span></div>{business?.show_prices_publicly&&<b>{money(s.price)}</b>}</button>)}</div><footer><span/><button className="button button-primary" disabled={!serviceId} onClick={()=>go("professional")}>Continuar</button></footer></>}
  {step==="professional"&&<><div className="public-heading"><h2>Escolha a profissional</h2><p>Conheça quem realizará seu atendimento.</p></div><div className="professional-choice-grid">{eligibleProfessionals.map(p=><button className={`professional-choice ${professionalId===p.id?"selected":""}`} key={p.id} onClick={()=>chooseProfessional(p.id)}>{p.photo_url?<img className="professional-photo" src={p.photo_url} alt={p.name}/>:<span>{p.name.slice(0,1)}</span>}<strong>{p.name}</strong>{business?.show_professional_specialty&&<small>{p.specialty}</small>}</button>)}</div><footer><button className="button button-secondary" onClick={()=>go("service")}>Voltar</button><button className="button button-primary" disabled={!professionalId} onClick={()=>go("date")}>Continuar</button></footer></>}
  {step==="date"&&<><div className="public-heading"><h2>Escolha a data</h2><p>É possível agendar nos próximos {business?.booking_window_days??60} dias.</p></div><div className="field"><label>Data do atendimento</label><input className="input" type="date" min={localDate()} max={localDate(business?.booking_window_days??60)} value={date} onChange={e=>{setDate(e.target.value);setTime("");setSlots([]);}}/></div>{date&&<div className="date-preview">{formatDate(date)}</div>}<footer><button className="button button-secondary" onClick={()=>go("professional")}>Voltar</button><button className="button button-primary" disabled={!date||loadingSlots} onClick={async()=>{await loadSlots(date);go("time");}}>{loadingSlots?"Consultando...":"Ver horários"}</button></footer></>}
  {step==="time"&&<><div className="public-heading"><h2>Escolha um horário</h2><p>{date?formatDate(date):"Selecione uma data"}</p></div>{loadingSlots?<div className="public-empty"><strong>Consultando horários...</strong></div>:<div className="slot-grid">{slots.map(s=><button className={time===s?"selected":""} key={s} onClick={()=>setTime(s)}>{s}</button>)}</div>}<footer><button className="button button-secondary" onClick={()=>go("date")}>Voltar</button><button className="button button-primary" disabled={!time} onClick={()=>go("customer")}>Continuar</button></footer></>}
  {step==="customer"&&<><div className="public-heading"><h2>Seus dados</h2><p>Seu WhatsApp será usado somente para informações deste atendimento.</p></div><div className="field"><label>Seu nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo"/></div><div className="field"><label>WhatsApp</label><input className="input" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(11) 99999-9999"/></div><footer><button className="button button-secondary" onClick={()=>go("time")}>Voltar</button><button className="button button-primary" disabled={!name.trim()||!phone.trim()} onClick={()=>go("review")}>Revisar</button></footer></>}
  {step==="review"&&<><div className="public-heading"><h2>Revise seu agendamento</h2><p>{manual?"O horário ficará reservado enquanto aguarda a confirmação da profissional.":"Seu horário será confirmado imediatamente."}</p></div>{manual&&<div className="notice-box" style={{marginBottom:16}}><strong>Confirmação pela profissional</strong><p>Você poderá receber uma mensagem pelo WhatsApp.</p></div>}<div className="booking-review"><div><small>Serviço</small><strong>{selectedService?.name}</strong><span>{selectedService?.duration_minutes} min</span></div><div><small>Profissional</small><strong>{selectedProfessional?.name}</strong></div><div><small>Data e horário</small><strong>{date&&formatDate(date)}</strong><span>{time} às {selectedService&&time?endTime(time,selectedService.duration_minutes):""}</span></div><div><small>Cliente</small><strong>{name}</strong><span>{phone}</span></div></div><footer><button className="button button-secondary" disabled={saving} onClick={()=>go("customer")}>Voltar</button><button className="button button-primary" disabled={saving} onClick={()=>void confirm()}>{saving?"Salvando...":manual?"Solicitar agendamento":"Confirmar agendamento"}</button></footer></>}
  {step==="success"&&<div className="booking-success"><div className="booking-success-icon">✓</div><span className="eyebrow">{manual?"Solicitação enviada":"Agendamento confirmado"}</span><h2>{manual?`Agora é só aguardar, ${name.split(" ")[0]}!`:`Está tudo certo, ${name.split(" ")[0]}!`}</h2><p>{manual?`Seu horário em ${business?.name} está aguardando a confirmação da profissional.`:`Seu horário em ${business?.name} foi reservado com sucesso.`}</p><div className="success-summary"><strong>{selectedService?.name}</strong><span>{date&&formatDate(date)} às {time}</span><span>com {selectedProfessional?.name}</span><b>{manual?"Status: aguardando confirmação":"Status: confirmado"}</b></div><button className="button button-secondary" onClick={()=>{setServiceId("");setProfessionalId("");setDate("");setTime("");setName("");setPhone("");setSlots([]);go("service");}}>Fazer outro agendamento</button></div>}
  </section><footer className="public-powered">Tecnologia de agendamento por <strong>Cruz Agenda</strong></footer>
 </main>;
}
