const appointments = [
  ["09:00", "Juliana Silva", "Design de sobrancelhas", "Maria"],
  ["10:30", "Ana Paula", "Design + henna", "Maria"],
  ["11:30", "Beatriz Santos", "Manicure", "Carla"],
  ["14:00", "Camila Oliveira", "Limpeza de pele", "Juliana"],
];

export default function DashboardPage() {
  return <div className="content"><div className="page-heading"><div><h1>Olá, Maria! 👋</h1><p>Aqui está o resumo do seu negócio hoje.</p></div><button className="button button-primary">+ Novo agendamento</button></div><section className="stats-grid"><div className="card stat-card"><span>Agendamentos hoje</span><strong>8</strong><small className="stat-positive">+2 em relação a ontem</small></div><div className="card stat-card"><span>Faturamento previsto</span><strong>R$ 960</strong><small className="stat-positive">+15% na semana</small></div><div className="card stat-card"><span>Clientes ativos</span><strong>128</strong><small className="stat-positive">+12 neste mês</small></div><div className="card stat-card"><span>Período gratuito</span><strong style={{color:"var(--pink)"}}>7 dias</strong><small className="table-muted">de 15 dias</small></div></section><section className="dashboard-grid"><div className="card panel"><div className="panel-header"><h3>Próximos atendimentos</h3><a className="table-muted" href="/painel/agenda">Ver agenda</a></div><div className="appointment-list">{appointments.map(([time,name,service,professional])=><div className="appointment-item" key={`${time}-${name}`}><strong>{time}</strong><div><b>{name}</b><br/><small>{service}</small></div><span className="badge badge-purple">{professional}</span></div>)}</div></div><div className="card panel"><div className="panel-header"><h3>Configuração da conta</h3><span className="badge badge-success">80%</span></div><div className="checklist">{["Dados do estabelecimento","Adicionar profissional","Adicionar serviço","Definir disponibilidade","Compartilhar seu link"].map((item,i)=><div className="check-item" key={item}><span className="check">{i<4?"✓":""}</span><span>{item}</span></div>)}</div><div style={{marginTop:24,padding:18,borderRadius:14,background:"var(--surface-soft)"}}><small className="table-muted">Seu link de agendamento</small><strong style={{display:"block",margin:"8px 0 14px",color:"var(--primary)"}}>cruzagenda.com/studio-bella</strong><button className="button button-primary">Copiar link</button></div></div></section></div>;
}
