import { notFound } from "next/navigation";

const pages: Record<string, { title: string; description: string; action: string; columns: string[]; rows: string[][] }> = {
  agenda: { title: "Agenda", description: "Visualize a rotina de toda a equipe.", action: "+ Novo agendamento", columns: ["Horário","Maria","Carla","Juliana"], rows: [["09:00","Design · Juliana","Manicure · Ana","Livre"],["10:00","Livre","Pedicure · Bia","Limpeza · Camila"],["11:00","Henna · Paula","Livre","Livre"],["14:00","Design · Larissa","Manicure · Clara","Peeling · Amanda"]] },
  agendamentos: { title: "Agendamentos", description: "Acompanhe, filtre e administre os atendimentos.", action: "+ Novo agendamento", columns: ["Cliente","Serviço","Profissional","Data","Status"], rows: [["Juliana Silva","Design de sobrancelhas","Maria","Hoje, 09:00","Confirmado"],["Ana Paula","Design + henna","Maria","Hoje, 10:30","Confirmado"],["Beatriz Santos","Manicure","Carla","Hoje, 11:30","Confirmado"]] },
  profissionais: { title: "Profissionais", description: "Gerencie quem atende no seu estabelecimento.", action: "+ Adicionar profissional", columns: ["Nome","Especialidade","Telefone","Status"], rows: [["Maria Silva","Sobrancelhas e henna","(11) 98888-7777","Ativo"],["Carla Mendes","Manicure e pedicure","(11) 97777-6666","Ativo"],["Juliana Costa","Estética facial","(11) 96666-5555","Ativo"]] },
  servicos: { title: "Serviços", description: "Defina duração, preço e profissionais responsáveis.", action: "+ Adicionar serviço", columns: ["Serviço","Duração","Preço","Profissionais","Status"], rows: [["Design de sobrancelhas","40 min","R$ 60,00","Maria","Ativo"],["Design + henna","60 min","R$ 80,00","Maria","Ativo"],["Manicure","50 min","R$ 45,00","Carla","Ativo"],["Limpeza de pele","90 min","R$ 150,00","Juliana","Ativo"]] },
  clientes: { title: "Clientes", description: "Consulte contatos e histórico de atendimentos.", action: "+ Adicionar cliente", columns: ["Cliente","WhatsApp","Atendimentos","Último atendimento"], rows: [["Juliana Silva","(11) 99999-1111","8","Hoje"],["Ana Paula","(11) 99999-2222","4","Hoje"],["Camila Oliveira","(11) 99999-3333","6","12/05/2026"]] },
  disponibilidade: { title: "Disponibilidade", description: "Configure horários por profissional e dia da semana.", action: "+ Novo bloqueio", columns: ["Dia","Maria","Carla","Juliana"], rows: [["Segunda","08:00–18:00","09:00–18:00","08:00–17:00"],["Terça","08:00–18:00","09:00–18:00","Folga"],["Quarta","Folga","09:00–18:00","08:00–17:00"],["Sábado","08:00–14:00","08:00–14:00","08:00–12:00"]] },
  "meu-link": { title: "Meu link", description: "Compartilhe sua página pública de agendamento.", action: "Copiar link", columns: ["Canal","Situação","Ação"], rows: [["WhatsApp","Pronto para compartilhar","Compartilhar"],["Instagram","Pronto para compartilhar","Adicionar à bio"],["Facebook","Pronto para compartilhar","Compartilhar"]] },
  configuracoes: { title: "Configurações", description: "Dados do negócio, preferências, aparência e assinatura.", action: "Salvar alterações", columns: ["Configuração","Valor atual","Situação"], rows: [["Nome do estabelecimento","Studio Bella","Configurado"],["Slug público","studio-bella","Disponível"],["Tema","Automático","Ativo"],["Antecedência mínima","2 horas","Ativo"],["Janela futura","60 dias","Ativo"]] },
};

export default async function SectionPage({ params }: { params: Promise<{ secao: string }> }) {
  const { secao } = await params;
  const page = pages[secao];
  if (!page) notFound();
  return <div className="content"><div className="page-heading"><div><h1>{page.title}</h1><p>{page.description}</p></div><button className="button button-primary">{page.action}</button></div><div className="card panel table-wrap"><table className="table"><thead><tr>{page.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{page.rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cellIndex===row.length-1?<span className="badge badge-success">{cell}</span>:cell}</td>)}</tr>)}</tbody></table></div></div>;
}
